# Build Stage
FROM --platform=linux/amd64 ubuntu:20.04 as builder
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y clang bison flex lld g++ make cmake

ADD . /nxdk
WORKDIR /nxdk
RUN make tools
ENV PATH=$PATH:/usr/lib/llvm-10/bin
